"""The distilled LOM inventory, baked into the package.

Generated by tools/distill_inventory.py from docs/lom-raw.json (runtime
introspection inside Live). The server uses it to refuse writes to unknown or
read-only properties before touching the wire (CONTRACT B.2), to check methods
and listeners exist, and to resolve enum values.

Class lookup is by bare class name with union merge: several LOM classes are
called "View", and the wire only reports the bare name. The bridge remains the
authority — a false positive here just means the bridge says no a moment later.
"""

import json
from importlib import resources

_data = None
_by_name = None


def _load():
    global _data, _by_name
    if _data is not None:
        return
    with resources.files("alberton_mcp.data").joinpath("lom_summary.json").open() as fh:
        _data = json.load(fh)
    _by_name = {}
    for qualname, entry in _data["classes"].items():
        bare = qualname.rsplit(".", 1)[-1]
        merged = _by_name.setdefault(bare, {"props": {}, "methods": set(),
                                            "listeners": set()})
        for prop, writable in entry["props"].items():
            merged["props"][prop] = merged["props"].get(prop, False) or writable
        merged["methods"].update(entry["methods"])
        merged["listeners"].update(entry["listeners"])


def known_class(class_name):
    _load()
    return class_name in _by_name


def writable(class_name, prop):
    """True/False if known; None when the class or prop is not in the inventory."""
    _load()
    entry = _by_name.get(class_name)
    if entry is None:
        return None
    return entry["props"].get(prop)


def has_method(class_name, method):
    _load()
    entry = _by_name.get(class_name)
    if entry is None:
        return None
    return method in entry["methods"]


def has_listener(class_name, prop):
    _load()
    entry = _by_name.get(class_name)
    if entry is None:
        return None
    return prop in entry["listeners"]


def props_of(class_name):
    _load()
    entry = _by_name.get(class_name)
    return dict(entry["props"]) if entry else {}


def enum_values(qualname):
    _load()
    return _data["enums"].get(qualname)
