#!/usr/bin/env python3
"""Render docs/lom-inventory.md from docs/lom-raw.json.

Runs outside Live (see tools/introspect/ for the in-Live dumper), so rendering
changes never cost a Live restart. The markdown is the greppable reference that
CLAUDE.md tells every session to check before designing against the LOM.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JSON_PATH = ROOT / "docs" / "lom-raw.json"
MD_PATH = ROOT / "docs" / "lom-inventory.md"

DOC_LIMIT = 110  # characters of docstring shown per member


def first_line(doc):
    """First meaningful line of a docstring, compacted."""
    if not doc:
        return ""
    for line in doc.splitlines():
        line = " ".join(line.split())
        if line:
            return line if len(line) <= DOC_LIMIT else line[: DOC_LIMIT - 1] + "…"
    return ""


def method_signature(doc):
    """Extract the Boost.Python signature line: 'name( (Cls)arg1, ...) -> Ret :'."""
    if not doc:
        return ""
    for line in doc.splitlines():
        line = line.strip()
        if "->" in line and "(" in line:
            line = line.rstrip(" :")
            line = re.sub(r"\(\s+\(", "((", line)
            return line if len(line) <= DOC_LIMIT else line[: DOC_LIMIT - 1] + "…"
    return first_line(doc)


def listeners_of(members):
    names = set()
    for name in members:
        if name.startswith("add_") and name.endswith("_listener"):
            names.add(name[len("add_") : -len("_listener")])
    return sorted(names)


def render_class(out, qualname, cls):
    out.append("### `%s`" % qualname)
    doc = first_line(cls.get("doc"))
    bases = [b for b in cls.get("bases", []) if b not in ("instance", "object")]
    meta = []
    if bases:
        meta.append("bases: " + ", ".join(bases))
    if doc:
        meta.append(doc)
    if meta:
        out.append("*%s*" % " — ".join(meta))
    out.append("")

    members = cls.get("members", {})
    listeners = listeners_of(members)

    props = {n: m for n, m in members.items() if m.get("kind") == "property"}
    if props:
        out.append("| property | writable | doc |")
        out.append("|---|---|---|")
        for name in sorted(props):
            member = props[name]
            writable = "RW" if member.get("writable") else "R"
            out.append("| `%s` | %s | %s |" % (name, writable, first_line(member.get("doc"))))
        out.append("")

    skip_listener = re.compile(r"^(add|remove)_.*_listener$|_has_listener$")
    methods = {
        n: m
        for n, m in members.items()
        if m.get("kind") == "method" and not skip_listener.search(n)
    }
    if methods:
        out.append("Methods:")
        out.append("")
        for name in sorted(methods):
            out.append("- `%s`" % method_signature(methods[name].get("doc")))
        out.append("")

    enums = {n: m for n, m in members.items() if m.get("kind") == "enum"}
    for name in sorted(enums):
        values = enums[name].get("values", {})
        pairs = ", ".join("%s=%s" % (k, v) for k, v in sorted(values.items(), key=lambda kv: kv[1]))
        out.append("Enum `%s.%s`: %s" % (qualname, name, pairs))
        out.append("")

    if listeners:
        out.append("Listeners (`add_/remove_/…_has_listener`): " + ", ".join("`%s`" % n for n in listeners))
        out.append("")

    other = {
        n: m
        for n, m in members.items()
        if m.get("kind") not in ("property", "method", "enum", "class")
        and not skip_listener.search(n)
    }
    if other:
        for name in sorted(other):
            member = other[name]
            out.append("- other `%s` (%s) %s" % (name, member.get("type"), first_line(member.get("doc"))))
        out.append("")

    for name, nested in sorted(cls.get("nested_classes", {}).items()):
        if "error" in nested and len(nested) == 1:
            out.append("### `%s.%s` — introspection error: %s" % (qualname, name, nested["error"]))
            out.append("")
            continue
        render_class(out, "%s.%s" % (qualname, name), nested)


def main():
    data = json.loads(JSON_PATH.read_text())
    meta = data.get("meta", {})
    live = meta.get("live_version", {})
    version = "%s.%s.%s" % (
        live.get("get_major_version", "?"),
        live.get("get_minor_version", "?"),
        live.get("get_bugfix_version", "?"),
    )

    out = []
    out.append("# LOM inventory — Live %s" % version)
    out.append("")
    out.append(
        "Generated by runtime introspection inside Ableton Live (`tools/introspect/`), "
        "rendered by `tools/render_inventory.py`. **Do not edit by hand; regenerate.**"
    )
    out.append("")
    out.append("- Live: %s" % version)
    out.append("- Python inside Live: `%s`" % meta.get("python", "?").split(" (")[0])
    out.append("- Dumped: %s (pass `%s`), platform `%s`" % (
        meta.get("generated_at", "?"), meta.get("pass", "?"), meta.get("platform", "?")))
    out.append("- Raw data with full docstrings and the instance-graph evidence: `docs/lom-raw.json`")
    out.append("")

    modules = data.get("modules", {})

    out.append("## Module index")
    out.append("")
    for module_name in sorted(modules):
        module = modules[module_name]
        class_names = sorted(module.get("classes", {}))
        enum_names = sorted(module.get("enums", {}))
        chunks = ", ".join("`%s`" % c for c in class_names + enum_names)
        out.append("- **%s**: %s" % (module_name, chunks if chunks else "(no classes)"))
    out.append("")

    for module_name in sorted(modules):
        module = modules[module_name]
        out.append("---")
        out.append("")
        out.append("## Module `Live.%s`" % module_name)
        mod_doc = first_line(module.get("doc"))
        if mod_doc and mod_doc != "None":
            out.append("*%s*" % mod_doc)
        out.append("")
        functions = module.get("functions", {})
        if functions:
            out.append("Module functions:")
            out.append("")
            for name in sorted(functions):
                out.append("- `%s`" % method_signature(functions[name].get("doc")))
            out.append("")
        for name in sorted(module.get("enums", {})):
            values = module["enums"][name].get("values", {})
            pairs = ", ".join("%s=%s" % (k, v) for k, v in sorted(values.items(), key=lambda kv: kv[1]))
            out.append("Enum `%s`: %s" % (name, pairs))
            out.append("")
        for name in sorted(module.get("classes", {})):
            render_class(out, name, module["classes"][name])

    MD_PATH.write_text("\n".join(out) + "\n")
    print("wrote %s (%d lines)" % (MD_PATH, len(out)))


if __name__ == "__main__":
    sys.exit(main())
